export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_CONFIRM_REQUEST = 'USER_CONFIRM_REQUEST';
export const USER_CONFIRM_SUCCESS = 'USER_CONFIRM_SUCCESS';
export const USER_CONFIRM_FAIL = 'USER_CONFIRM_FAIL';

export const USER_CONTACT_REQUEST = 'USER_CONTACT_REQUEST';
export const USER_CONTACT_SUCCESS = 'USER_CONTACT_SUCCESS';
export const USER_CONTACT_FAIL = 'USER_CONTACT_FAIL';

export const USER_UPDATE_USER_REQUEST = 'USER_UPDATE_USER_REQUEST';
export const USER_UPDATE_USER_SUCCESS = 'USER_UPDATE_USER_SUCCESS';
export const USER_UPDATE_USER_FAIL = 'USER_UPDATE_USER_FAIL';

export const USER_UPDATE_PASS_REQUEST = 'USER_UPDATE_PASS_REQUEST';
export const USER_UPDATE_PASS_SUCCESS = 'USER_UPDATE_PASS_SUCCESS';
export const USER_UPDATE_PASS_FAIL = 'USER_UPDATE_PASS_FAIL';

export const USER_FORGOT_REQUEST = 'USER_FORGOT_REQUEST';
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS';
export const USER_FORGOT_FAIL = 'USER_FORGOT_FAIL';

export const USER_RESET_REQUEST = 'USER_RESET_REQUEST';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_RESET_FAIL = 'USER_RESET_FAIL';